from . import stock_move_line
from . import stock_move
from . import mrp_production
from . import stock_picking
from . import stock_quant
from . import stock_production_lot
from . import mrp_workorder
from . import product_uom
from . import product_template
from . import product_product
from . import purchase_order
from . import product_category
from . import license_plate
from . import license_plate_line
from . import res_partner
from . import stock_picking_type
from . import stock_barcode_lot
from . import stock_inventory_line
